# Generated by Django 5.2.9 on 2025-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcategory_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
